language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_HADOOP_VERSION="2.6.0" TEST_SPARK_VERSION="1.5.2"
script:
  - sbt -Dhadoop.testVersion=$TEST_HADOOP_VERSION -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
after_success:
  - bash <(curl -s https://codecov.io/bash)
